import { MigrationInterface, QueryRunner } from "typeorm";

export class AddOtpBuilder1785999195011 implements MigrationInterface {
    name = 'AddOtpBuilder1785999195011'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "otp_api_keys" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "hashedSecretKey" varchar(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "lastUsedAt" varchar)`);
        await queryRunner.query(`CREATE TABLE "otp_templates" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "name" varchar(100) NOT NULL, "body" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "otp_requests" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "templateId" varchar, "phone" varchar(20) NOT NULL, "hashedOtp" varchar(255) NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('pending'), "attempts" integer NOT NULL DEFAULT (0), "expiresAt" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "otp_applications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "name" varchar(100) NOT NULL, "whatsappSenderId" varchar, "otpLength" integer NOT NULL DEFAULT (4), "expiryMinutes" integer NOT NULL DEFAULT (10), "maxAttempts" integer NOT NULL DEFAULT (3), "cooldownSeconds" integer NOT NULL DEFAULT (60), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "otp_webhooks" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "url" varchar(500) NOT NULL, "events" text NOT NULL DEFAULT ('[]'), "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "otp_webhook_deliveries" ("id" varchar PRIMARY KEY NOT NULL, "webhookId" varchar NOT NULL, "applicationId" varchar NOT NULL, "requestId" varchar, "eventType" varchar(50) NOT NULL, "destinationUrl" varchar(500) NOT NULL, "httpStatus" integer, "responseBody" text, "retryCount" integer NOT NULL DEFAULT (0), "nextRetryTime" varchar, "lastAttempt" varchar, "status" varchar(20) NOT NULL DEFAULT ('pending'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "otp_logs" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "requestId" varchar, "action" varchar(50) NOT NULL, "detail" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "temporary_otp_api_keys" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "hashedSecretKey" varchar(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "lastUsedAt" varchar, CONSTRAINT "FK_8d3eeba91c4e4654487eb29cf96" FOREIGN KEY ("applicationId") REFERENCES "otp_applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_otp_api_keys"("id", "applicationId", "hashedSecretKey", "isActive", "createdAt", "updatedAt", "lastUsedAt") SELECT "id", "applicationId", "hashedSecretKey", "isActive", "createdAt", "updatedAt", "lastUsedAt" FROM "otp_api_keys"`);
        await queryRunner.query(`DROP TABLE "otp_api_keys"`);
        await queryRunner.query(`ALTER TABLE "temporary_otp_api_keys" RENAME TO "otp_api_keys"`);
        await queryRunner.query(`CREATE TABLE "temporary_otp_templates" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "name" varchar(100) NOT NULL, "body" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_c6a0ae49daa45898a4e7edbf299" FOREIGN KEY ("applicationId") REFERENCES "otp_applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_otp_templates"("id", "applicationId", "name", "body", "createdAt", "updatedAt") SELECT "id", "applicationId", "name", "body", "createdAt", "updatedAt" FROM "otp_templates"`);
        await queryRunner.query(`DROP TABLE "otp_templates"`);
        await queryRunner.query(`ALTER TABLE "temporary_otp_templates" RENAME TO "otp_templates"`);
        await queryRunner.query(`CREATE TABLE "temporary_otp_requests" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "templateId" varchar, "phone" varchar(20) NOT NULL, "hashedOtp" varchar(255) NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('pending'), "attempts" integer NOT NULL DEFAULT (0), "expiresAt" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_6c94e15c8816eb2641fec2e60f7" FOREIGN KEY ("applicationId") REFERENCES "otp_applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_otp_requests"("id", "applicationId", "templateId", "phone", "hashedOtp", "status", "attempts", "expiresAt", "createdAt", "updatedAt") SELECT "id", "applicationId", "templateId", "phone", "hashedOtp", "status", "attempts", "expiresAt", "createdAt", "updatedAt" FROM "otp_requests"`);
        await queryRunner.query(`DROP TABLE "otp_requests"`);
        await queryRunner.query(`ALTER TABLE "temporary_otp_requests" RENAME TO "otp_requests"`);
        await queryRunner.query(`CREATE TABLE "temporary_otp_applications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "name" varchar(100) NOT NULL, "whatsappSenderId" varchar, "otpLength" integer NOT NULL DEFAULT (4), "expiryMinutes" integer NOT NULL DEFAULT (10), "maxAttempts" integer NOT NULL DEFAULT (3), "cooldownSeconds" integer NOT NULL DEFAULT (60), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_eae5a1fe954f34e1501f5c59e6d" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_otp_applications"("id", "userId", "name", "whatsappSenderId", "otpLength", "expiryMinutes", "maxAttempts", "cooldownSeconds", "createdAt", "updatedAt") SELECT "id", "userId", "name", "whatsappSenderId", "otpLength", "expiryMinutes", "maxAttempts", "cooldownSeconds", "createdAt", "updatedAt" FROM "otp_applications"`);
        await queryRunner.query(`DROP TABLE "otp_applications"`);
        await queryRunner.query(`ALTER TABLE "temporary_otp_applications" RENAME TO "otp_applications"`);
        await queryRunner.query(`CREATE TABLE "temporary_otp_webhooks" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "url" varchar(500) NOT NULL, "events" text NOT NULL DEFAULT ('[]'), "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_b5723214477456051bfb3e5ff7a" FOREIGN KEY ("applicationId") REFERENCES "otp_applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_otp_webhooks"("id", "applicationId", "url", "events", "isActive", "createdAt", "updatedAt") SELECT "id", "applicationId", "url", "events", "isActive", "createdAt", "updatedAt" FROM "otp_webhooks"`);
        await queryRunner.query(`DROP TABLE "otp_webhooks"`);
        await queryRunner.query(`ALTER TABLE "temporary_otp_webhooks" RENAME TO "otp_webhooks"`);
        await queryRunner.query(`CREATE TABLE "temporary_otp_webhook_deliveries" ("id" varchar PRIMARY KEY NOT NULL, "webhookId" varchar NOT NULL, "applicationId" varchar NOT NULL, "requestId" varchar, "eventType" varchar(50) NOT NULL, "destinationUrl" varchar(500) NOT NULL, "httpStatus" integer, "responseBody" text, "retryCount" integer NOT NULL DEFAULT (0), "nextRetryTime" varchar, "lastAttempt" varchar, "status" varchar(20) NOT NULL DEFAULT ('pending'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_2f3327124845632fba8160a08d1" FOREIGN KEY ("webhookId") REFERENCES "otp_webhooks" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_otp_webhook_deliveries"("id", "webhookId", "applicationId", "requestId", "eventType", "destinationUrl", "httpStatus", "responseBody", "retryCount", "nextRetryTime", "lastAttempt", "status", "createdAt", "updatedAt") SELECT "id", "webhookId", "applicationId", "requestId", "eventType", "destinationUrl", "httpStatus", "responseBody", "retryCount", "nextRetryTime", "lastAttempt", "status", "createdAt", "updatedAt" FROM "otp_webhook_deliveries"`);
        await queryRunner.query(`DROP TABLE "otp_webhook_deliveries"`);
        await queryRunner.query(`ALTER TABLE "temporary_otp_webhook_deliveries" RENAME TO "otp_webhook_deliveries"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "otp_webhook_deliveries" RENAME TO "temporary_otp_webhook_deliveries"`);
        await queryRunner.query(`CREATE TABLE "otp_webhook_deliveries" ("id" varchar PRIMARY KEY NOT NULL, "webhookId" varchar NOT NULL, "applicationId" varchar NOT NULL, "requestId" varchar, "eventType" varchar(50) NOT NULL, "destinationUrl" varchar(500) NOT NULL, "httpStatus" integer, "responseBody" text, "retryCount" integer NOT NULL DEFAULT (0), "nextRetryTime" varchar, "lastAttempt" varchar, "status" varchar(20) NOT NULL DEFAULT ('pending'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "otp_webhook_deliveries"("id", "webhookId", "applicationId", "requestId", "eventType", "destinationUrl", "httpStatus", "responseBody", "retryCount", "nextRetryTime", "lastAttempt", "status", "createdAt", "updatedAt") SELECT "id", "webhookId", "applicationId", "requestId", "eventType", "destinationUrl", "httpStatus", "responseBody", "retryCount", "nextRetryTime", "lastAttempt", "status", "createdAt", "updatedAt" FROM "temporary_otp_webhook_deliveries"`);
        await queryRunner.query(`DROP TABLE "temporary_otp_webhook_deliveries"`);
        await queryRunner.query(`ALTER TABLE "otp_webhooks" RENAME TO "temporary_otp_webhooks"`);
        await queryRunner.query(`CREATE TABLE "otp_webhooks" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "url" varchar(500) NOT NULL, "events" text NOT NULL DEFAULT ('[]'), "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "otp_webhooks"("id", "applicationId", "url", "events", "isActive", "createdAt", "updatedAt") SELECT "id", "applicationId", "url", "events", "isActive", "createdAt", "updatedAt" FROM "temporary_otp_webhooks"`);
        await queryRunner.query(`DROP TABLE "temporary_otp_webhooks"`);
        await queryRunner.query(`ALTER TABLE "otp_applications" RENAME TO "temporary_otp_applications"`);
        await queryRunner.query(`CREATE TABLE "otp_applications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "name" varchar(100) NOT NULL, "whatsappSenderId" varchar, "otpLength" integer NOT NULL DEFAULT (4), "expiryMinutes" integer NOT NULL DEFAULT (10), "maxAttempts" integer NOT NULL DEFAULT (3), "cooldownSeconds" integer NOT NULL DEFAULT (60), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "otp_applications"("id", "userId", "name", "whatsappSenderId", "otpLength", "expiryMinutes", "maxAttempts", "cooldownSeconds", "createdAt", "updatedAt") SELECT "id", "userId", "name", "whatsappSenderId", "otpLength", "expiryMinutes", "maxAttempts", "cooldownSeconds", "createdAt", "updatedAt" FROM "temporary_otp_applications"`);
        await queryRunner.query(`DROP TABLE "temporary_otp_applications"`);
        await queryRunner.query(`ALTER TABLE "otp_requests" RENAME TO "temporary_otp_requests"`);
        await queryRunner.query(`CREATE TABLE "otp_requests" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "templateId" varchar, "phone" varchar(20) NOT NULL, "hashedOtp" varchar(255) NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('pending'), "attempts" integer NOT NULL DEFAULT (0), "expiresAt" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "otp_requests"("id", "applicationId", "templateId", "phone", "hashedOtp", "status", "attempts", "expiresAt", "createdAt", "updatedAt") SELECT "id", "applicationId", "templateId", "phone", "hashedOtp", "status", "attempts", "expiresAt", "createdAt", "updatedAt" FROM "temporary_otp_requests"`);
        await queryRunner.query(`DROP TABLE "temporary_otp_requests"`);
        await queryRunner.query(`ALTER TABLE "otp_templates" RENAME TO "temporary_otp_templates"`);
        await queryRunner.query(`CREATE TABLE "otp_templates" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "name" varchar(100) NOT NULL, "body" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "otp_templates"("id", "applicationId", "name", "body", "createdAt", "updatedAt") SELECT "id", "applicationId", "name", "body", "createdAt", "updatedAt" FROM "temporary_otp_templates"`);
        await queryRunner.query(`DROP TABLE "temporary_otp_templates"`);
        await queryRunner.query(`ALTER TABLE "otp_api_keys" RENAME TO "temporary_otp_api_keys"`);
        await queryRunner.query(`CREATE TABLE "otp_api_keys" ("id" varchar PRIMARY KEY NOT NULL, "applicationId" varchar NOT NULL, "hashedSecretKey" varchar(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "lastUsedAt" varchar)`);
        await queryRunner.query(`INSERT INTO "otp_api_keys"("id", "applicationId", "hashedSecretKey", "isActive", "createdAt", "updatedAt", "lastUsedAt") SELECT "id", "applicationId", "hashedSecretKey", "isActive", "createdAt", "updatedAt", "lastUsedAt" FROM "temporary_otp_api_keys"`);
        await queryRunner.query(`DROP TABLE "temporary_otp_api_keys"`);
        await queryRunner.query(`DROP TABLE "otp_logs"`);
        await queryRunner.query(`DROP TABLE "otp_webhook_deliveries"`);
        await queryRunner.query(`DROP TABLE "otp_webhooks"`);
        await queryRunner.query(`DROP TABLE "otp_applications"`);
        await queryRunner.query(`DROP TABLE "otp_requests"`);
        await queryRunner.query(`DROP TABLE "otp_templates"`);
        await queryRunner.query(`DROP TABLE "otp_api_keys"`);
    }

}
